baseURL = "https://www.musfiqrfarhan.blog/"
title   = "Musfiq R Farhan"

defaultContentLanguage = "en"
enableEmoji            = true
pluralizeListTitles    = false
timeZone               = "Asia/Dhaka"

[languages]
  [languages.en]
    direction = 'ltr'
    label     = 'English'
    locale    = 'en-US'
    weight    = 1

[markup]
  [markup.highlight]
    noClasses  = false
    style      = 'solarized-dark'

[params]
  description = "Official blog and portfolio of Musfiq R Farhan, Actor & Public Figure"

[taxonomies]
  category = 'categories'
  tag      = 'tags'

[services]
  [services.googleAnalytics]
    ID = 'G-MBZGKNMDWC'
